// frontend/src/pages/Register.vue
<script lang="ts" setup>
	import logo from "@img/logo_black.svg";
	import { useCustomFetch } from "@composable/useCustomFetch.ts";
	import { ref } from "vue";
	import type { registerForm } from "@interfaces/auth.interface.ts";
	import { useRouter } from "vue-router";

	const router = useRouter();

	const payload = ref<registerForm>({
		username: "",
		email: "",
		password: "",
		confirm_password: "",
	});

	const handleRegister = async () => {
		try {
			await useCustomFetch("/register", {
				method: "POST",
				body: JSON.stringify(payload.value),
			});
			await router.push("/");
		} catch (error) {
			console.log(error);
		}
	};
</script>

<template>
	<div id="register">
		<form class="register" @submit.prevent="handleRegister">
			<header>
				<h1>Register</h1>
				<img :src="logo" alt="Logo" />
			</header>
			<input
				id="username"
				v-model="payload.username"
				minlength="3"
				name="username"
				placeholder="Username.."
				required
				type="text" />
			<input id="email" v-model="payload.email" name="email" placeholder="Email.." required type="email" />
			<input
				id="password"
				v-model="payload.password"
				name="password"
				placeholder="Password.."
				required
				type="password" />
			<input
				id="confirm_password"
				v-model="payload.confirm_password"
				name="confirm_password"
				placeholder="Confirm Password.."
				required
				type="password" />
			<div class="actions">
				<button type="submit">Register</button>
				<div class="link">
					<RouterLink to="/login">Already an Account ?</RouterLink>
				</div>
			</div>
		</form>
	</div>
</template>

// frontend/src/app/pages/register/register.component.ts
import { Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import {
  FormControl,
  FormGroup,
  FormsModule,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { registerForm } from '@shared/interfaces/auth.interface';
import { ConfigService } from '@core/service/configService';

@Component({
  selector: 'app-register',
  imports: [RouterLink, FormsModule, ReactiveFormsModule],
  templateUrl: './register.component.html',
  styleUrl: './register.component.scss',
})
export class RegisterComponent {
  private service: ConfigService = inject(ConfigService);
  registerForm: FormGroup<registerForm> = new FormGroup({
    username: new FormControl('', [Validators.required, Validators.min(3)]),
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [
      Validators.required,
      Validators.minLength(6),
    ]),
    password_confirmation: new FormControl('', [
      Validators.required,
      Validators.minLength(6),
    ]),
  });

  imagePath: string = 'image/logo_black.svg';

  onSubmit() {
    const { username, password_confirmation, password, email } =
      this.registerForm.controls;
    if (password_confirmation.value !== password.value) {
      console.log(password.value, password_confirmation.value);
      return;
    }
    this.service.http
      .post(
        `http://localhost:8080/api/auth/register`,
        JSON.stringify({
          username: username.value,
          password: password.value,
          email: email.value,
        }),
      )
      .subscribe((data) => {
        console.log(data);
      });
  }
}

<section id="register">
  <form class="register" [formGroup]="registerForm" (ngSubmit)="onSubmit()">
    <header>
      <h1>Register</h1>
      <img [src]="imagePath" alt="logo" />
    </header>
    <input
      type="text"
      placeholder="Username"
      min="3"
      id="username"
      formControlName="username"
      [required]="true"
    />
    <input
      type="email"
      placeholder="Email"
      id="email"
      formControlName="email"
      [required]="true"

    />
    <input
      type="password"
      placeholder="Password"
      min="6"
      id="password"
      formControlName="password"
      [required]="true"

    />
    <input
      type="password"
      placeholder="Confirm Password"
      min="6"
      id="confirm_password"
      formControlName="password_confirmation"
      [required]="true"
    />
    <div class="actions">
      <button type="submit">Register</button>
      <div class="link">
        <span><a routerLink="/login">Already an Account ?</a></span>
      </div>
    </div>
  </form>
</section>
