// front/pages/login.vue
<script setup lang="ts">
import CustomCheckbox from '~/components/Checkbox/LoginCustomCheckbox.vue';
import {useUserStore} from "~/stores/useUserStore";
import type {User} from "~/types/global";

useHead({title: 'Login - Tempest Board'})

const data = reactive({
  email: '',
  password: '',
  remember: false,
});
const errors = reactive({
  msg: '',
});

const handleCheckboxChange = (newValue: any) => {
  data.remember = newValue;
};

const handleSubmit = async () => {
  const res = await useCustomFetch('/login/', {
    method: 'post',
    body: JSON.stringify(data),
  });
  if (res.data.value != null) {
    const user = res.data.value as User;
    useUserStore().setUser(user);
    await navigateTo('/');
  } else {
    errors.msg = res.error.value?.data?.msg || 'An error occurred';
  }
};


</script>
<template>
  <div id="Auth">
    <div>
      <form @submit.prevent="handleSubmit()" id="login">
        <div>
          <label>Email</label>
          <input
              id="email"
              type="email"
              name="email"
              v-model="data.email"
              class="input"
          />
        </div>
        <div>
          <label>Password</label>
          <input
              id="password"
              type="password"
              name="password"
              v-model="data.password"
              class="input"
          />
          <div class="error">{{ errors.msg }}</div>
        </div>
        <CustomCheckbox
            label="Remember me"
            @update:checked="handleCheckboxChange"
            v-model="data.remember"
        />
        <div>
          <NuxtLink to="#">Forgotten password ?</NuxtLink>
          <button type="submit">
            Login
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

// resources/js/Pages/Login.tsx
import { Head, useForm } from "@inertiajs/react";
import AuthLayout from "@/Layouts/AuthLayout";
import CustomCheckbox from "@/Componants/checkbox";
import { FormEventHandler, useEffect } from "react";

export default function () {
    const { data, setData, post, processing, errors, reset } = useForm({
        email: "",
        password: "",
        remember: false,
    });

    useEffect(() => {
        return () => {
            reset("password");
        };
    }, []);
    const handleSubmit: FormEventHandler = (e) => {
        e.preventDefault();
        post("/login");
    };

    return (
        <AuthLayout>
            <Head title="Login" />
            <form onSubmit={handleSubmit} id="login">
                <div>
                    <label>Email</label>
                    <input
                        id="email"
                        type="email"
                        name="email"
                        value={data.email}
                        onChange={(e) => setData("email", e.target.value)}
                    />
                    {errors.email && (
                        <div className="error">{errors.email}</div>
                    )}
                </div>
                <div>
                    <label>Password</label>
                    <input
                        id="password"
                        type="password"
                        name="password"
                        value={data.password}
                        onChange={(e) => setData("password", e.target.value)}
                    />
                    {errors.password && (
                        <div className="error">{errors.password}</div>
                    )}
                </div>
                <CustomCheckbox
                    label="Remember me"
                    checked={data.remember}
                    onChange={(e) => {
                        data.remember = e.target.checked;
                    }}
                />
                <div>
                    <span>Forgotten password ?</span>
                    <button type="submit" disabled={processing}>
                        Login
                    </button>
                </div>
            </form>
        </AuthLayout>
    );
}
