// resources/js/Componants/Issue/IssueModal.tsx
import { CustomPriority } from "@/Componants/Icons/Priority";
import { IssueModalProps, Project } from "@/types";
import { useEffect, useRef, useState } from "react";
import { useForm } from "@inertiajs/react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faAnglesUp, faChevronDown, faCircleExclamation, faMinus, faPause } from "@fortawesome/free-solid-svg-icons";
import { priorityEnum } from "@/enums/global";
import { IconProp } from "@fortawesome/fontawesome-svg-core";
import { CanceledIssueIcon, CompletedIssueIcon, InProgressIssueIcon, OpenIssueIcon } from "@/Componants/Icons/StateIcon";

export default function ({ projects, showModal, setShowModal, state }: IssueModalProps) {
    const { data, setData, post, processing, errors, reset } = useForm({
        project_id: 0,
        title: "",
        description: "",
        priority: "NEUTRAL",
        status: "open",
    });
    const [count, setCount] = useState(0);
    const [dropdownOpen, setDropdownOpen] = useState(false);
    const [htmlPriority, setHtmlPriority] = useState<React.ReactNode | null>(null);
    const [htmlState, setHtmlState] = useState<React.ReactNode | null>(null);
    const [projectDropdownOpen, setProjectDropdownOpen] = useState(false);
    const [projectName, setProjectName] = useState("");
    const [stateDropdownOpen, setStateDropdownOpen] = useState(false);
    const handleSetPriority = (priorityValue: string, iconName: IconProp) => {
        const PE = Object.keys(priorityEnum).filter(v => v === priorityValue)[0];
        if (data.priority === priorityValue) {
            setHtmlPriority(null);
            setData("priority", "NEUTRAL");
            setDropdownOpen(false);
            return;
        }
        setHtmlPriority(<CustomPriority label={PE} iconName={iconName} />);
        setData("priority", priorityValue);
        setDropdownOpen(false);
    };
    const handleSetState = (stateValue: string, iconComponant: React.ReactNode) => {
        if (data.status === stateValue && stateDropdownOpen) {
            setHtmlState(null);
            setData("status", "open");
            setStateDropdownOpen(false);
            return;
        }
        setHtmlState(iconComponant);
        setData("status", stateValue);
        setStateDropdownOpen(false);
    };
    const handleCancel = () => {
        reset();
        setHtmlPriority(null);
        setProjectName("");
        setShowModal(false);
    };
    const handleSetProject = (projectId: number, projectNameParams: string) => {
        if (projectName == projectNameParams && projectId == data.project_id) {
            setProjectName("");
            setData("project_id", 0);
            setProjectDropdownOpen(false);
            return;
        }
        setProjectName(projectNameParams);
        setData("project_id", projectId);
        setProjectDropdownOpen(false);
    };

    const modalRef = useRef<HTMLDivElement>(null);
    const priorityDPRef = useRef<HTMLDivElement>(null);
    const projectDPRef = useRef<HTMLDivElement>(null);
    const stateDPRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        switch (state) {
            case "open":
                handleSetState(
                    "open",
                    <div className="dropdown-icon">
                        Open <OpenIssueIcon />
                    </div>,
                );
                break;
            case "in_progress":
                handleSetState(
                    "in_progress",
                    <div className="dropdown-icon">
                        In Progress <InProgressIssueIcon />
                    </div>,
                );
                break;
            case "completed":
                handleSetState(
                    "completed",
                    <div className="dropdown-icon">
                        Completed <CompletedIssueIcon />
                    </div>,
                );
                break;
            case "canceled":
                handleSetState(
                    "canceled",
                    <div className="dropdown-icon">
                        Canceled <CanceledIssueIcon />
                    </div>,
                );
                break;
            default:
                break;
        }
        const handlerCloseModal = (e: any) => {
            if (!modalRef.current?.contains(e.target)) {
                if (showModal) handleCancel();
            }
            if (!priorityDPRef.current?.contains(e.target)) {
                setDropdownOpen(false);
            }
            if (!projectDPRef.current?.contains(e.target)) {
                setProjectDropdownOpen(false);
            }
            if (!stateDPRef.current?.contains(e.target)) {
                setStateDropdownOpen(false);
            }
        };
        document.addEventListener("mousedown", handlerCloseModal);
        document.addEventListener("keydown", event => {
            if (event.key === "Escape") {
                setShowModal(false);
            }
        });
        if (errors.title || errors.description) setShowModal(true);
        return () => {
            document.addEventListener("mousedown", handlerCloseModal);
            reset();
        };
    }, [errors, showModal]);

    return (
        <div className={showModal ? "modal is-active" : "modal"}>
            <div className="modal-background"></div>
            <div className="modal-card" ref={modalRef}>
                <header className="modal-card-head">
                    <p className="modal-card-title">Create Issue</p>
                    <button className="delete" aria-label="close" onClick={() => setShowModal(false)}></button>
                </header>
                <section className="modal-card-body">
                    <div className="field">
                        <div className="control">
                            <input className="input" type="text" placeholder="Issue Title" maxLength={100} minLength={3} value={data.title} onChange={e => setData("title", e.target.value)} />
                            {errors.title && <p className="help is-danger">{errors.title}</p>}
                            <textarea
                                className="textarea has-fixed-size"
                                placeholder="Issue Description"
                                maxLength={500}
                                minLength={3}
                                value={data.description}
                                onInput={e => {
                                    setCount(500 - (e.target as any).value.length);
                                }}
                                onChange={e => setData("description", e.target.value)}></textarea>
                            {errors.description && <p className="help is-danger">{errors.description}</p>}
                            <div className="count">{count != 0 ? count : "500"}/500</div>
                            <div className={dropdownOpen ? "dropdown is-active" : "dropdown"} ref={priorityDPRef}>
                                <div className="dropdown-trigger">
                                    <button className="button" aria-haspopup="true" aria-controls="dropdown-priority" onClick={() => setDropdownOpen(!dropdownOpen)}>
                                        {htmlPriority ? (
                                            htmlPriority
                                        ) : (
                                            <div>
                                                <span>Priority</span>
                                                <span className="icon">
                                                    <FontAwesomeIcon icon={faChevronDown} />
                                                </span>
                                            </div>
                                        )}
                                    </button>
                                </div>
                                <div className="dropdown-menu" id="dropdown-priority" role="menu">
                                    <div className="dropdown-content">
                                        <div className="dropdown-item" onClick={() => handleSetPriority("URGENT", faCircleExclamation)}>
                                            <CustomPriority label="URGENT" iconName={faCircleExclamation} />
                                        </div>
                                        <div className="dropdown-item" onClick={() => handleSetPriority("HIGH", faAnglesUp)}>
                                            <CustomPriority label="HIGH" iconName={faAnglesUp} />
                                        </div>
                                        <div className="dropdown-item" onClick={() => handleSetPriority("NEUTRAL", faPause)}>
                                            <CustomPriority label="NEUTRAL" iconName={faPause} rotate={90} />
                                        </div>
                                        <div className="dropdown-item" onClick={() => handleSetPriority("LOW", faMinus)}>
                                            <CustomPriority label="LOW" iconName={faMinus} />
                                        </div>
                                        <div className="dropdown-item" onClick={() => handleSetPriority("MINOR", faChevronDown)}>
                                            <CustomPriority label="MINOR" iconName={faChevronDown} />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className={projectDropdownOpen ? "dropdown is-active" : "dropdown"} ref={projectDPRef}>
                                <div className="dropdown-trigger">
                                    <button className="button" aria-haspopup="true" aria-controls="dropdown-project" onClick={() => setProjectDropdownOpen(!projectDropdownOpen)}>
                                        {projectName ? (
                                            <div>
                                                <span>{projectName}</span>
                                                <span className="icon">
                                                    <FontAwesomeIcon icon={faChevronDown} />
                                                </span>
                                            </div>
                                        ) : (
                                            <div>
                                                <span>Project</span>
                                                <span className="icon">
                                                    <FontAwesomeIcon icon={faChevronDown} />
                                                </span>
                                            </div>
                                        )}
                                    </button>
                                </div>
                                <div className="dropdown-menu" id="dropdown-project" role="menu">
                                    <div className="dropdown-content">
                                        {projects.map((project: Project) => {
                                            return (
                                                <div
                                                    className="dropdown-item"
                                                    key={project.id}
                                                    onClick={() => {
                                                        handleSetProject(project.id, project.name);
                                                    }}>
                                                    {project.name}
                                                </div>
                                            );
                                        })}
                                    </div>
                                </div>
                            </div>
                            <div className={stateDropdownOpen ? "dropdown is-active" : "dropdown"} ref={stateDPRef}>
                                <div className="dropdown-trigger">
                                    <button className="button" aria-haspopup="true" aria-controls="dropdown-state" onClick={() => setStateDropdownOpen(!projectDropdownOpen)}>
                                        {htmlState ? (
                                            htmlState
                                        ) : (
                                            <>
                                                <span>State</span>
                                                <span className="icon">
                                                    <FontAwesomeIcon icon={faChevronDown} />
                                                </span>
                                            </>
                                        )}
                                    </button>
                                </div>
                                <div className="dropdown-menu" id="dropdown-project" role="menu">
                                    <div className="dropdown-content">
                                        <div
                                            className="dropdown-item dropdown-icon"
                                            onClick={() =>
                                                handleSetState(
                                                    "open",
                                                    <div className="dropdown-icon">
                                                        Open <OpenIssueIcon />
                                                    </div>,
                                                )
                                            }>
                                            Open
                                            <OpenIssueIcon />
                                        </div>
                                        <div
                                            className="dropdown-item dropdown-icon"
                                            onClick={() =>
                                                handleSetState(
                                                    "in_progress",
                                                    <div className="dropdown-icon">
                                                        In Progress <InProgressIssueIcon />
                                                    </div>,
                                                )
                                            }>
                                            In Progress
                                            <InProgressIssueIcon />
                                        </div>
                                        <div
                                            className="dropdown-item dropdown-icon"
                                            onClick={() =>
                                                handleSetState(
                                                    "completed",
                                                    <div className="dropdown-icon">
                                                        Completed <CompletedIssueIcon />
                                                    </div>,
                                                )
                                            }>
                                            Completed
                                            <CompletedIssueIcon />
                                        </div>
                                        <div
                                            className="dropdown-item dropdown-icon"
                                            onClick={() =>
                                                handleSetState(
                                                    "canceled",
                                                    <div className="dropdown-icon">
                                                        Canceled <CanceledIssueIcon />
                                                    </div>,
                                                )
                                            }>
                                            Canceled
                                            <CanceledIssueIcon />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <footer className="modal-card-foot">
                    <button
                        className="button btn-success"
                        onClick={() => {
                            if (errors.title || errors.description) {
                                setShowModal(true);
                            }
                            post("/issue", {
                                preserveScroll: true,
                                onSuccess: () => {
                                    setShowModal(false);
                                    reset();
                                },
                            });
                        }}
                        disabled={processing}>
                        Create
                    </button>
                    <button className="button btn-error" onClick={() => handleCancel()}>
                        Cancel
                    </button>
                </footer>
            </div>
        </div>
    );
}

// front/components/Modals/IssueModal.vue
<script lang="ts" setup>
import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";
import {reactive, ref, watch} from 'vue'
import type {Project} from "~/types/global";
import IssueIcon from "~/components/Icon/IssueIcon.vue";
import PriorityIcon from "~/components/Icon/PriorityIcon.vue";
import {useUserStore} from "~/stores/useUserStore";

interface Props {
  projects: Project[];
  state?: string;
}

const props = defineProps<Props>()

const showModal = defineModel('modal', {type: Boolean, required: true})
const count = ref(500);
const dropdownOpen = ref(false);
const projectDropdownOpen = ref(false);
const stateDropdownOpen = ref(false);
const SelectedProject = ref("Project");
const SelectedState = ref("State");
const SelectedPriority = ref("Priority");
const priorityIcon = ref("fa-solid fa-chevron-down");
const stateIcon = ref("fa-solid fa-chevron-down")
const user = useUserStore().getUser();
const {isRefresh} = useRefreshData();

const handleClose = () => {
  dropdownOpen.value = false;
  projectDropdownOpen.value = false;
  stateDropdownOpen.value = false;
}

onBeforeUnmount(() => {
  document.removeEventListener('click', handleClose)
  document.removeEventListener('keydown', event => {
    if (event.key === 'Escape') {
      showModal.value = false
    }
  })
})

onMounted(() => {
  document.addEventListener('click', handleClose)
  document.addEventListener('keydown', event => {
    if (event.key === 'Escape') {
      showModal.value = false
      resetForm()
    }
  })
})

const data = reactive({
  creator: user?.id,
  assigned: user?.id,
  title: "",
  description: "",
  priority: "",
  project: 0,
  status: props.state ? props.state : "",
  tags: null
});

const errors = reactive({
  title: "",
  description: "",
});


watch(() => props.state, (newVal) => {
  if (newVal) handleSetState(newVal);
});

const resetForm = () => {
  data.title = "";
  data.description = "";
  data.priority = "";
  data.project = 0;
  data.status = "";
  SelectedProject.value = "Project";
  SelectedState.value = "State";
  SelectedPriority.value = "Priority";
  priorityIcon.value = "fa-solid fa-chevron-down";
  stateIcon.value = "fa-solid fa-chevron-down";
};


const handleSetPriority = (priority: string) => {
  if (SelectedPriority.value === priority) SelectedPriority.value = "Priority";
  else {
    data.priority = priority.toUpperCase();
    if (priority === "urgent") priorityIcon.value = "fa-solid fa-circle-exclamation";
    else if (priority === "high") priorityIcon.value = "fa-solid fa-angles-up";
    else if (priority === "neutral") priorityIcon.value = "fa-solid fa-pause";
    else if (priority === "low") priorityIcon.value = "fa-solid fa-minus";
    else if (priority === "minor") priorityIcon.value = "fa-solid fa-chevron-down";
    SelectedPriority.value = priority.charAt(0).toUpperCase() + priority.slice(1);
  }
};

const handleSetState = (state: string) => {
  if (SelectedState.value === state) SelectedState.value = "State";
  else {
    data.status = state;
    if (state === "open") stateIcon.value = "fa-regular fa-circle";
    else if (state === "completed") stateIcon.value = "fa-solid fa-circle";
    else if (state === "canceled") stateIcon.value = "fa-solid fa-circle-xmark";
    SelectedState.value = state.charAt(0).toUpperCase() + state.slice(1);
  }
};

const handleSetProject = (id: number, name: string) => {
  if (SelectedProject.value === name) {
    data.project = 0;
    SelectedProject.value = "Project";
  } else {
    data.project = id;
    SelectedProject.value = name;
  }
};

const handleSubmit = async () => {
  if (data.title.length < 3) errors.title = "Title must be at least 3 characters long";
  if (data.description.length < 3) errors.description = "Description must be at least 3 characters long";
  const res = await useCustomFetch('/issues/', {
        method: 'POST',
        body: JSON.stringify(data),
      }
  )
  if (res.error.value !== null) {
    errors.title = res.error.value?.data.title[0];
    errors.description = res.error.value?.data.description[0];
  }
  if (res.data.value !== null) {
    isRefresh.value = true
    showModal.value = false;
  }
};


</script>

<template>
  <div :class="{'is-active': showModal}" class="modal">
    <div class="modal-background"></div>
    <div ref={modalRef} class="modal-card">
      <header class="modal-card-head">
        <p class="modal-card-title">Create Issue</p>
        <button aria-label="close" class="delete" @click="showModal=false"></button>
      </header>
      <section class="modal-card-body">
        <div class="field">
          <div class="control">
            <input class="input" maxLength=100 minLength=3 placeholder="Issue Title" type="text" v-model="data.title">
            <p v-if="errors.title" class="help is-danger">{{ errors.title }}</p>
            <textarea
                class="textarea has-fixed-size"
                maxLength=500
                minLength=3
                placeholder="Issue Description"
                @input="count = 500 - ($event.target as HTMLTextAreaElement).value.length"
                v-model="data.description"
            ></textarea>
            <p v-if="errors.description" class="help is-danger">{{ errors.description }}</p>
            <div class="count">{{ count != 0 ? count : 0 }}/500</div>

            <div :class="{'is-active': dropdownOpen}" class="dropdown">
              <div class="dropdown-trigger">
                <button aria-controls="dropdown-priority" aria-haspopup="true" class="button" @click.stop="dropdownOpen=!dropdownOpen">
                  <span>{{ SelectedPriority }}</span>
                  <span class="icon">
                    <font-awesome-icon :icon="priorityIcon" :rotation="SelectedPriority == 'Neutral' ? 90 : 0"/>
                  </span>
                </button>
              </div>
              <div id="dropdown-priority" class="dropdown-menu" role="menu">
                <div class="dropdown-content">
                  <div class="dropdown-item" @click="handleSetPriority('urgent')">
                    <div class="priority">
                      <span>Urgent</span>
                      <span class="icon">
                        <PriorityIcon priority="URGENT"/>
                      </span>
                    </div>
                  </div>
                  <div class="dropdown-item" @click="handleSetPriority('high')">
                    <div class="priority">
                      <span>High</span>
                      <span class="icon">
                        <PriorityIcon priority="HIGH"/>
                      </span>
                    </div>
                  </div>
                  <div class="dropdown-item" @click="handleSetPriority('neutral')">
                    <div class="priority">
                      <span>Neutral</span>
                      <span class="icon">
                        <PriorityIcon priority="NEUTRAL"/>
                      </span>
                    </div>
                  </div>
                  <div class="dropdown-item" @click="handleSetPriority('low')">
                    <div class="priority">
                      <span>Low</span>
                      <span class="icon">
                        <PriorityIcon priority="LOW"/>
                      </span>
                    </div>
                  </div>
                  <div class="dropdown-item" @click="handleSetPriority('minor')">
                    <div class="priority">
                      <span>Minor</span>
                      <span class="icon">
                        <PriorityIcon priority="MINOR"/>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div :class="{'is-active': projectDropdownOpen}" class="dropdown">
              <div class="dropdown-trigger">
                <button aria-controls="dropdown-project" aria-haspopup="true" class="button" @click.stop="projectDropdownOpen=!projectDropdownOpen">
                  <span>{{ SelectedProject }}</span>
                  <span class="icon">
                    <font-awesome-icon icon="fa-solid fa-chevron-down"/>
                  </span>
                </button>
              </div>
              <div id="dropdown-project" class="dropdown-menu" role="menu">
                <div class="dropdown-content">
                  <div v-for="project in projects" class="dropdown-item">
                    <div @click="handleSetProject(project.id, project.name)">
                      {{ project.name }}
                    </div>
                  </div>
                </div>
              </div>
            </div>


            <div :class="{'is-active': stateDropdownOpen}" class="dropdown">
              <div class="dropdown-trigger">
                <button aria-controls="dropdown-state" aria-haspopup="true" class="button" @click.stop="stateDropdownOpen=!stateDropdownOpen">
                  <span>{{ SelectedState }}</span>
                  <span class="icon dropdown-icon">
                    <span :class="{'open-issue-icon': SelectedState == 'Open', 'completed-issue-icon': SelectedState == 'Completed', 'canceled-issue-icon': SelectedState == 'Canceled'}">
                      <font-awesome-icon v-if="SelectedState != 'In_progress'" :icon="stateIcon"/>
                    </span>
                    <IssueIcon state="in_progress" v-if="SelectedState == 'In_progress'"/>
                  </span>
                </button>
              </div>
              <div id="dropdown-project" class="dropdown-menu" role="menu">
                <div class="dropdown-content">
                  <div class="dropdown-item dropdown-icon" @click="handleSetState('open')">
                    Open
                    <IssueIcon state="open"/>
                  </div>
                  <div class="dropdown-item dropdown-icon" @click="handleSetState('in_progress')">
                    In Progress
                    <IssueIcon state="in_progress"/>
                  </div>
                  <div class="dropdown-item dropdown-icon" @click="handleSetState('completed')">
                    Completed
                    <IssueIcon state="completed"/>
                  </div>
                  <div class="dropdown-item dropdown-icon" @click="handleSetState('canceled')">
                    Canceled
                    <IssueIcon state="canceled"/>
                  </div>
                </div>
              </div>
            </div>


          </div>
        </div>
      </section>
      <footer class="modal-card-foot">
        <button class="button btn-error" @click="showModal=false; resetForm()">
          Cancel
        </button>
        <button
            class="button btn-success" @click="handleSubmit()">
          Create
        </button>
      </footer>
    </div>
  </div>
</template>
