// front/components/Navbar.vue
<script setup lang="ts">
import {onBeforeUnmount, onMounted, ref} from "vue";
import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";
import type {Project, User} from "~/types/global";
import IssueModal from "~/components/Modals/IssueModal.vue";
import MenuProject from "~/components/Menu/MenuProject.vue";

interface Props {
  user: User
  projects: Project[]
}

const props = defineProps<Props>()

const isDropDownOpen = ref(false);
const isMenuOpen = ref(false)
const isShowModal = ref(false)
const thumbnail = ref('')

onMounted(() => {
  document.addEventListener('click', () => isDropDownOpen.value = false)
  if (props.user.thumbnail) {
    thumbnail.value = props.user.thumbnail
  }
})

onBeforeUnmount(() => {
  document.removeEventListener('click', () => isDropDownOpen.value = false)
})


const logout = async () => {
  await useCustomFetch('/logout/', {
    method: 'GET'
  })
  useUserStore().setUser(null)
  navigateTo('/login')
}


</script>

<template>
  <IssueModal :projects="projects" v-model:modal="isShowModal"/>
  <div id="navbar">
    <div>
      <div>
        <img src="https://placehold.co/30" alt=""/>
        <h1>
          <NuxtLink to="/">Tempest Board</NuxtLink>
        </h1>
        <div :class="{'is-active' : isDropDownOpen}" class="dropdown is-right">
          <div class="dropdown-trigger" aria-controls="user-menu" aria-haspopup="true" @click.stop="isDropDownOpen = !isDropDownOpen">
            <img v-if="thumbnail" :src="thumbnail" alt="user thumbnail" class="dropdown-thumbnail"/>
            <img v-else src="assets/image/user.png" alt="user thumbnail" class="dropdown-thumbnail"/>
          </div>
          <div class="dropdown-menu" id="user-menu">
            <div class="dropdown-content">
              <ul>
                <li>
                  <NuxtLink to="#">Profile</NuxtLink>
                </li>
                <li>
                  <NuxtLink to="#">Settings</NuxtLink>
                </li>
                <li>
                  <NuxtLink to="/project">Project</NuxtLink>
                </li>
                <li>
                  <button @click="logout()">
                    Logout
                  </button>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="button-container">
      <button @click="isShowModal = true">
        <font-awesome-icon icon="fa-solid fa-pen-to-square"/>
        New Issue
      </button>
      <button>
        <font-awesome-icon icon="fa-solid fa-magnifying-glass"/>
      </button>
    </div>

    <nav>
      <ul>
        <li class="is-active">
          <NuxtLink to="/">My Issues</NuxtLink>
        </li>

        <li v-for="project in projects">
          <MenuProject :project="project"/>
        </li>

        <li>
          <NuxtLink to="#">Roadmap</NuxtLink>
        </li>
        <li>
          <NuxtLink to="#">Dashboard</NuxtLink>
        </li>
      </ul>
    </nav>
  </div>
</template>

// resources/js/Componants/NavBar.tsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
    faChevronRight,
    faMagnifyingGlass,
    faPenToSquare,
} from "@fortawesome/free-solid-svg-icons";
import { Link } from "@inertiajs/react";
import { NavBarProps, Project } from "@/types";
import { useState } from "react";

export default function ({ projects, user }: NavBarProps) {
    const [isMenuOpen, setIsMenuOpen] = useState(false);
    return (
        <>
            <div id="navbar">
                <div>
                    <div>
                        <img src="https://placehold.co/30" alt="" />
                        <h1>Tempest Board</h1>
                        <div className="dropdown is-hoverable is-right">
                            <div className="dopdown-trigger">
                                <img
                                    src={user.thumbnail}
                                    alt="user thumbnail"
                                    aria-haspopup="true"
                                    aria-controls="user-menu"
                                />
                            </div>
                            <div
                                className="dropdown-menu"
                                id="user-menu"
                                role="menu"
                            >
                                <div className="dropdown-content">
                                    <ul>
                                        <li>
                                            <Link href="#">Profile</Link>
                                        </li>
                                        <li>
                                            <Link href="#">Settings</Link>
                                        </li>
                                        <li>
                                            <Link
                                                method="post"
                                                href={route("logout")}
                                                as={"button"}
                                            >
                                                Logout
                                            </Link>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="button-container">
                        <button>
                            <FontAwesomeIcon icon={faPenToSquare} />
                            New Issue
                        </button>
                        <button>
                            <FontAwesomeIcon icon={faMagnifyingGlass} />
                        </button>
                    </div>
                </div>

                <nav>
                    <ul>
                        <li>
                            <Link href="#">My Issues</Link>
                        </li>
                        {projects.map((project: Project) => {
                            return (
                                <li key={project.id}>
                                    <div className="menu is-menu">
                                        <div className="menu-list">
                                            <div
                                                className="menu-button"
                                                onClick={() =>
                                                    setIsMenuOpen(!isMenuOpen)
                                                }
                                            >
                                                <span className="">
                                                    {project.name}
                                                </span>
                                                <FontAwesomeIcon
                                                    icon={faChevronRight}
                                                    className={
                                                        isMenuOpen
                                                            ? "is-menu-open"
                                                            : ""
                                                    }
                                                />
                                            </div>
                                            <div
                                                className={
                                                    isMenuOpen
                                                        ? "is-menu-list"
                                                        : "is-menu-list is-menu-close"
                                                }
                                            >
                                                <ul className="menu-list">
                                                    <li>
                                                        <span>Issues</span>
                                                        <ul>
                                                            <li>
                                                                <Link href="#">
                                                                    Active
                                                                </Link>
                                                            </li>
                                                            <li>
                                                                <Link href="#">
                                                                    Backlog
                                                                </Link>
                                                            </li>
                                                        </ul>
                                                    </li>
                                                    <li>
                                                        <Link href="#">
                                                            Releases
                                                        </Link>
                                                    </li>
                                                    <li>
                                                        <span>Repos</span>
                                                        <ul>
                                                            <li>
                                                                <Link href="#">
                                                                    Pull
                                                                    Requests
                                                                </Link>
                                                            </li>
                                                            <li>
                                                                <Link href="#">
                                                                    Issues
                                                                </Link>
                                                            </li>
                                                        </ul>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            );
                        })}

                        <li>
                            <Link href="#">Roadmap</Link>
                        </li>
                        <li>
                            <Link href="#">Dashboard</Link>
                        </li>
                    </ul>
                </nav>
            </div>
        </>
    );
}
