// frontend/src/app/pages/login/login.component.ts
import { Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import {
  FormControl,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { loginForm } from '@shared/interfaces/auth.interface';
import { ConfigService } from '@core/service/configService';

@Component({
  selector: 'app-login',
  imports: [RouterLink, ReactiveFormsModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss',
})
export class LoginComponent {
  private service: ConfigService = inject(ConfigService);
  loginForm: FormGroup<loginForm> = new FormGroup({
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required]),
  });
  imagePath: string = 'image/logo_black.svg';

  onSubmit() {
    const { password, email } = this.loginForm.controls;
    this.service.http
      .post(`http://localhost/api/api/auth/login`, {
        password: password.value,
        email: email.value,
      })
      .subscribe((data) => {
        console.log(data);
      });
  }
}

<section id="login">
  <form class="login" [formGroup]="loginForm" (ngSubmit)="onSubmit()">
    <header>
      <h1>Login</h1>
      <img [src]="imagePath" alt="logo" />
    </header>
    <input
      type="email"
      placeholder="Email"
      id="email"
      formControlName="email"
    />
    <input
      type="password"
      placeholder="Password"
      id="password"
      formControlName="password"
    />
    <div class="actions">
      <button type="submit">Login</button>
      <div class="link">
        <span><a routerLink="">Forgot Password ?</a></span>
        <span><a routerLink="/register">No Account ?</a></span>
      </div>
    </div>
  </form>
</section>

// frontend/src/pages/Login.vue
<script lang="ts" setup>
	import logo from "@img/logo_black.svg";
	import { useCustomFetch } from "@composable/useCustomFetch.ts";
	import { ref } from "vue";
	import type { loginForm } from "@interfaces/auth.interface.ts";
	import { useRouter } from "vue-router";

	const router = useRouter();

	const payload = ref<loginForm>({
		email: "",
		password: "",
	});

	const handleLogin = async () => {
		try {
			await useCustomFetch("/login", {
				method: "POST",
				body: JSON.stringify(payload.value),
			});
			await router.push("/");
		} catch (error) {
			console.log(error);
		}
	};
</script>

<template>
	<div id="login">
		<form class="login" @submit.prevent="handleLogin">
			<header>
				<h1>Login</h1>
				<img :src="logo" alt="Logo" />
			</header>
			<input id="email" v-model="payload.email" name="email" placeholder="Email.." required type="email" />
			<input
				id="password"
				v-model="payload.password"
				name="password"
				placeholder="Password.."
				required
				type="password" />
			<div class="actions">
				<button type="submit">Login</button>
				<div class="link">
					<span>Forgot Password ?</span>
					<RouterLink to="/register">No Account ?</RouterLink>
				</div>
			</div>
		</form>
	</div>
</template>
