// front/components/Issue/IssueList.vue
<script setup lang="ts">

import type {Issue, Project} from "~/types/global";
import IssueListDetails from "~/components/Issue/IssueListDetails.vue";

interface Props {
  issueArray: Issue[];
  createdIssue: Issue[];
  assignedIssue: Issue[];
  Projects: Project[];
  typeView: string;
}

defineProps<Props>()
defineEmits(['isCreated']);
</script>

<template>
  <IssueListDetails v-if="typeView === 'all'" :issueArray="issueArray" :Projects="Projects"/>
  <IssueListDetails v-if="typeView === 'created'" :issueArray="createdIssue" :Projects="Projects"/>
  <IssueListDetails v-if="typeView === 'assigned'" :issueArray="assignedIssue" :Projects="Projects"/>
</template>

// resources/js/Componants/Issue/IssueList.tsx
import { Issue, Project } from "@/types";
import { IssueListDetails } from "@/Componants/Issue/IssueListDetails";

interface IssueListProps {
    issueArray: Issue[];
    createdIssue: Issue[];
    assignedIssue: Issue[];
    Projects: Project[];
    typeView: string;
}

export const IssueList: React.FC<IssueListProps> = ({ issueArray, Projects, assignedIssue, createdIssue, typeView }) => {
    return (
        <>
            {typeView === "all" ? (
                <>
                    <IssueListDetails issueArray={issueArray} Projects={Projects} />
                </>
            ) : typeView === "created" ? (
                <>
                    <IssueListDetails issueArray={createdIssue} Projects={Projects} />
                </>
            ) : (
                <>
                    <IssueListDetails issueArray={assignedIssue} Projects={Projects} />
                </>
            )}
        </>
    );
};
